export const SET_ALL_ROOMS = 'SET_ALL_ROOMS';
export const SET_EMPTY_ROOMS = 'SET_EMPTY_ROOMS';
export const SET_CURRENT_ROOM = 'SET_CURRENT_ROOM';
export const RESET_CURRENT_ROOM = 'RESET_CURRENT_ROOM';

export const FETCH_ALL_USERS = 'FETCH_ALL_USERS';
export const GET_CURRENT_USER_ID = 'GET_CURRENT_USER_ID';




