export const SET_ALL_ROOMS = 'SET_ALL_ROOMS';
export const SET_EMPTY_ROOMS = 'SET_EMPTY_ROOMS';
export const SET_CURRENT_ROOM = 'SET_CURRENT_ROOM';
export const RESET_CURRENT_ROOM = 'RESET_CURRENT_ROOM';
export const SET_ROOM_MESSAGES = 'SET_ROOM_MESSAGES';
export const RESET_ROOM_MESSAGES = 'RESET_ROOM_MESSAGES';


export const FETCH_ALL_USERS = 'FETCH_ALL_USERS';
export const GET_CURRENT_USER_ID = 'GET_CURRENT_USER_ID';


export const CHANGE_STATS_PANEL_STATUS = 'CHANGE_STATS_PANEL_STATUS';


