const GET_EMPTY_ROOMS = 'GET_EMPTY_ROOMS';
const GET_AMOUNT_OF_ROOMS = 'GET_EMPTY_ROOMS';
const GET_AMOUNT_OF_USERS = 'GET_AMOUNT_OF_USERS';

export default {
    GET_EMPTY_ROOMS,
    GET_AMOUNT_OF_USERS,
    GET_AMOUNT_OF_ROOMS
}